// Code generated by MockGen. DO NOT EDIT.
// Source: statepool.go

// Package iosbase_mock is a generated GoMock package.
package iostdb

import (
	"github.com/golang/mock/gomock"
)

// MockStatePool is a mock of StatePool interface
type MockStatePool struct {
	ctrl     *gomock.Controller
	recorder *MockStatePoolMockRecorder
}

// MockStatePoolMockRecorder is the mock recorder for MockStatePool
type MockStatePoolMockRecorder struct {
	mock *MockStatePool
}

