// Code generated by MockGen. DO NOT EDIT.
// Source: blockchain.go

// Package iosbase_mock is a generated GoMock package.
package iostdb

import (
	gomock "github.com/golang/mock/gomock"
	. "github.com/iost-official/Go-IOS-Protocol/iosbase"
	reflect "reflect"
)

// MockBlockChain is a mock of BlockChain interface
type MockBlockChain struct {
	ctrl     *gomock.Controller
	recorder *MockBlockChainMockRecorder
}

// MockBlockChainMockRecorder is the mock recorder for MockBlockChain
type MockBlockChainMockRecorder struct {
	mock *MockBlockChain
}

