// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/iost-official/prototype/db (interfaces: Database)

// Package db_mock is a generated GoMock package.
package db_mock

import (
	"github.com/golang/mock/gomock"
)

// MockDatabase is a mock of Database interface
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

