// Code generated by MockGen. DO NOT EDIT.
// Source: network.go

// Package iosbase_mock is a generated GoMock package.
package iosbase_mock

import (
	gomock "github.com/golang/mock/gomock"
	. "github.com/iost-official/Go-IOS-Protocol/iosbase"
	reflect "reflect"
)

// MockNetwork is a mock of Network interface
type MockNetwork struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkMockRecorder
}

// MockNetworkMockRecorder is the mock recorder for MockNetwork
type MockNetworkMockRecorder struct {
	mock *MockNetwork
}

