// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/iost-official/Go-IOS-Protocol/iosbase (interfaces: TxPool)

// Package iosbase_mock is a generated GoMock package.
package iosbase

import (
	gomock "github.com/golang/mock/gomock"
	iosbase "github.com/iost-official/Go-IOS-Protocol/iosbase"
	reflect "reflect"
)

// MockTxPool is a mock of TxPool interface
type MockTxPool struct {
	ctrl     *gomock.Controller
	recorder *MockTxPoolMockRecorder
}

// MockTxPoolMockRecorder is the mock recorder for MockTxPool
type MockTxPoolMockRecorder struct {
	mock *MockTxPool
}

