// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/iost-official/prototype/network (interfaces: Router)

// Package protocol_mock is a generated GoMock package.
package protocol_mock

import "github.com/golang/mock/gomock"

// MockRouter is a mock of Router interface
type MockRouter struct {
	ctrl     *gomock.Controller
	recorder *MockRouterMockRecorder
}

// MockRouterMockRecorder is the mock recorder for MockRouter
type MockRouterMockRecorder struct {
	mock *MockRouter
}
