// Code generated by MockGen. DO NOT EDIT.
// Source: blockchain.go

// Package iosbase_mock is a generated GoMock package.
package db

import (
	"github.com/golang/mock/gomock"
)

// MockBlockChain is a mock of BlockChain interface
type MockBlockChain struct {
	ctrl     *gomock.Controller
	recorder *MockBlockChainMockRecorder
}


