// Code generated by MockGen. DO NOT EDIT.
// Source: statepool.go

// Package iosbase_mock is a generated GoMock package.
package db

import (
	"github.com/golang/mock/gomock"
)

// MockStatePool is a mock of StatePool interface
type MockStatePool struct {
	ctrl     *gomock.Controller
	recorder *MockStatePoolMockRecorder
}


