// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/iost-official/prototype/core (interfaces: TxPool)

// Package core_mock is a generated GoMock package.
package core_mock

import (
"github.com/golang/mock/gomock"
)

// MockTxPool is a mock of TxPool interface
type MockTxPool struct {
	ctrl     *gomock.Controller
	recorder *MockTxPoolMockRecorder
}

// MockTxPoolMockRecorder is the mock recorder for MockTxPool
type MockTxPoolMockRecorder struct {
	mock *MockTxPool
}

